spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update  # Options: create, update, validate, none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true  # Enable H2 console for debugging
